rsreset
def LC_END                   rb 1 ;
def LC_TYPE                  rb 1 ; type
def LC_RECT                  rb 1 ; x y w h
def LC_SINGLE                rb 1 ; x y

def LC_FILL_PLACEHOLDERS     rb 1 ; type

; ---------------------------------------------------------
def LEVEL_AREA_1 EQU $F8
def LEVEL_AREA_2 EQU $F9
def LEVEL_AREA_3 EQU $FA
def LEVEL_AREA_4 EQU $FB
def LEVEL_AREA_5 EQU $FC
def LEVEL_AREA_6 EQU $FD
def LEVEL_AREA_7 EQU $FE
def LEVEL_AREA_8 EQU $FF
