rsreset
def LC_END                   rw 1 ;
def LC_TYPE                  rw 1 ; type
def LC_RECT                  rw 1 ; x y w h
def LC_SINGLE                rw 1 ; x y
def LC_FILL_PLACEHOLDERS     rw 1 ; type

; ---------------------------------------------------------
def LEVEL_AREA_1 EQUS "BlockType_PlaceholderArea1"
def LEVEL_AREA_2 EQUS "BlockType_PlaceholderArea2"
def LEVEL_AREA_3 EQUS "BlockType_PlaceholderArea3"
def LEVEL_AREA_4 EQUS "BlockType_PlaceholderArea4"
def LEVEL_AREA_5 EQUS "BlockType_PlaceholderArea5"
def LEVEL_AREA_6 EQUS "BlockType_PlaceholderArea6"
def LEVEL_AREA_7 EQUS "BlockType_PlaceholderArea7"
def LEVEL_AREA_8 EQUS "BlockType_PlaceholderArea8"
